export default new Map<string, string>([
  ["games-and-software", "🎮"],
  ["car-insurance-and-maintenance", "🚗"],
  ["family", "👨‍👩‍👧‍👦"],
  ["good-life", "👍"],
  ["groceries", "🛒"],
  ["booze", "🍺"],
  ["clothing-and-accessories", "👕"],
  ["cycling", "🚴"],
  ["homeware-and-appliances", "🏠"],
  ["personal", "👤"],
  ["education-and-student-loans", "🧠"],
  ["events-and-gigs", "🎤"],
  ["fuel", "⛽"],
  ["home", "🏠"],
  ["internet", "🌐"],
  ["fitness-and-wellbeing", "🏋️"],
  ["hobbies", "🎨"],
  ["home-maintenance-and-improvements", "🔨"],
  ["parking", "🅿️"],
  ["transport", "🚗"],
  ["gifts-and-charity", "🎁"],
  ["holidays-and-travel", "✈️"],
  ["pets", "🐱"],
  ["public-transport", "🚌"],
  ["hair-and-beauty", "💈"],
  ["lottery-and-gambling", "🎲"],
  ["home-insurance-and-rates", "🏠"],
  ["car-repayments", "🚗"],
  ["health-and-medical", "🏥"],
  ["pubs-and-bars", "🍻"],
  ["rent-and-mortgage", "🏠"],
  ["taxis-and-share-cars", "🚕"],
  ["investments", "📈"],
  ["restaurants-and-cafes", "🍴"],
  ["toll-roads", "🚗"],
  ["utilities", "💡"],
  ["life-admin", "📝"],
  ["takeaway", "🍕"],
  ["mobile-phone", "📱"],
  ["tobacco-and-vaping", "🚬"],
  ["news-magazines-and-books", "📰"],
  ["tv-and-music", "📺"],
  ["adult", "🔞"],
  ["technology", "📱"],
]);
