import { CategoryDetails } from "./types.ts";
export default <CategoryDetails> {
  tree: [
    {
      id: "good-life",
      children: [
        { id: "games-and-software" },
        { id: "takeaway" },
        { id: "holidays-and-travel" },
        { id: "hobbies" },
        { id: "tv-and-music" },
        { id: "restaurants-and-cafes" },
        { id: "pubs-and-bars" },
        { id: "events-and-gigs" },
        { id: "lottery-and-gambling" },
        { id: "booze" },
        { id: "adult" },
        // { id: "tobacco-and-vaping" },
      ],
    },
    {
      id: "personal",
      children: [
        { id: "life-admin" },
        { id: "technology" },
        { id: "mobile-phone" },
        { id: "clothing-and-accessories" },
        { id: "health-and-medical" },
        { id: "hair-and-beauty" },
        { id: "news-magazines-and-books" },
        { id: "gifts-and-charity" },
        { id: "family" },
        // { id: "fitness-and-wellbeing" },
        // { id: "education-and-student-loans" },
        // { id: "investments" },
      ],
    },
    {
      id: "home",
      children: [
        { id: "groceries" },
        { id: "pets" },
        { id: "rent-and-mortgage" },
        { id: "utilities" },
        { id: "internet" },
        { id: "homeware-and-appliances" },
        { id: "home-maintenance-and-improvements" },
        // { id: "home-insurance-and-rates" },
      ],
    },
    {
      id: "transport",
      children: [
        { id: "fuel" },
        { id: "public-transport" },
        { id: "toll-roads" },
        { id: "taxis-and-share-cars" },
        { id: "parking" },
        { id: "car-insurance-and-maintenance" },
        // { id: "cycling" },
        // { id: "car-repayments" },
      ],
    },
  ],
  names: new Map<string, string>([
    ["games-and-software", "Apps, Games & Software"],
    ["car-insurance-and-maintenance", "Car Insurance, Rego & Maintenance"],
    ["family", "Children & Family"],
    ["good-life", "Good Life"],
    ["groceries", "Groceries"],
    ["booze", "Booze"],
    ["clothing-and-accessories", "Clothing & Accessories"],
    ["cycling", "Cycling"],
    ["homeware-and-appliances", "Homeware & Appliances"],
    ["personal", "Personal"],
    ["education-and-student-loans", "Education & Student Loans"],
    ["events-and-gigs", "Events & Gigs"],
    ["fuel", "Fuel"],
    ["home", "Home"],
    ["internet", "Internet"],
    ["fitness-and-wellbeing", "Fitness & Wellbeing"],
    ["hobbies", "Hobbies"],
    ["home-maintenance-and-improvements", "Maintenance & Improvements"],
    ["parking", "Parking"],
    ["transport", "Transport"],
    ["gifts-and-charity", "Gifts & Charity"],
    ["holidays-and-travel", "Holidays & Travel"],
    ["pets", "Pets"],
    ["public-transport", "Public Transport"],
    ["hair-and-beauty", "Hair & Beauty"],
    ["lottery-and-gambling", "Lottery & Gambling"],
    ["home-insurance-and-rates", "Rates & Insurance"],
    ["car-repayments", "Repayments"],
    ["health-and-medical", "Health & Medical"],
    ["pubs-and-bars", "Pubs & Bars"],
    ["rent-and-mortgage", "Rent & Mortgage"],
    ["taxis-and-share-cars", "Taxis & Share Cars"],
    ["investments", "Investments"],
    ["restaurants-and-cafes", "Restaurants & Cafes"],
    ["toll-roads", "Tolls"],
    ["utilities", "Utilities"],
    ["life-admin", "Life Admin"],
    ["takeaway", "Takeaway"],
    ["mobile-phone", "Mobile Phone"],
    ["tobacco-and-vaping", "Tobacco & Vaping"],
    ["news-magazines-and-books", "News, Magazines & Books"],
    ["tv-and-music", "TV, Music & Streaming"],
    ["adult", "Adult"],
    ["technology", "Technology"],
  ]),
};
